### ISSUE TITLE
Как это работает

### ISSUE THREAD

**Issue by mrsortie** [JackRichardson666/DiscordAccountGenerator#1]
Как это работает

**Comment by Eld3rly** [comment]
Всем привет, остальным соболезную.
Читайте здесь [howtouse](https://github.com/JackRichardson666/DiscordAccountGenerator/blob/main/howtouse.txt)
А дальше кабанище опишет вам как его юзать подробнее

**Comment by JackRichardson666** [comment]
Привет, данный софт использует вебдрайвер, если ты знаешь js или nodejs ты можешь залезть в код и увидеть как действует вебдрайвер, куда жмет, куда пишет и что делает.
